---
# 这个剧本在所有节点上运行
- name: 安装基础包
  yum:
    name:
      - conntrack
      - ipvsadm
      - ipset
      - jq
      - sysstat
      - curl
      - iptables
      - libseccomp

- name: 关闭firewalld
  service: name=firewalld state=stopped enabled=no
  
- name: 关闭selinux
  lineinfile:
    dest: /etc/selinux/config
    regexp: "^SELINUX="
    line: "SELINUX=disabled"
  
- name: 关闭swap
  lineinfile:
    dest: /etc/fstab
    regexp: ".*swap"
    line: ""

- name: 即时生效
  shell: setenforce 0 ; swapoff -a

- name: 拷贝时区
  copy: src=/usr/share/zoneinfo/Asia/Shanghai dest=/etc/localtime

- name: 添加hosts
  template: src=hosts.j2 dest=/etc/hosts 

- name: 加载内核模块
  modprobe: name={{ item }} state=present
  with_items:
    - br_netfilter
    - ip_vs

- name: 复制kubernetes.conf
  template: src=kubernetes.conf dest=/etc/sysctl.d/kubernetes.conf  force=yes

- name: 运行kubernetes.conf
  shell: "sysctl -p /etc/sysctl.d/kubernetes.conf"
  ignore_errors: true

- name: 运行kubernetes.conf
  shell: "sysctl -p /etc/sysctl.d/kubernetes.conf"

- name: 运行kubernetes.conf
  shell: mount -t cgroup -o cpu,cpuacct none /sys/fs/cgroup/cpu,cpuacct
  ignore_errors: true
#- name: 同步系统时间
#  yum: name=ntpdate state=present
#- name: 同步系统时间
#  shell: ntpdate time.windows.com

